package de.greenrobot.daoexample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NOTE.
 */
public class Note {

    /** Not-null value. */
    private String text;
    private String comment;
    private java.util.Date date;
    private Long mAaa;
    private Integer isBaa;
    private Integer aa;

    public Note() {
    }

    public Note(String text, String comment, java.util.Date date, Long mAaa, Integer isBaa, Integer aa) {
        this.text = text;
        this.comment = comment;
        this.date = date;
        this.mAaa = mAaa;
        this.isBaa = isBaa;
        this.aa = aa;
    }

    /** Not-null value. */
    public String getText() {
        return text;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setText(String text) {
        this.text = text;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Long getMAaa() {
        return mAaa;
    }

    public void setMAaa(Long mAaa) {
        this.mAaa = mAaa;
    }

    public Integer getIsBaa() {
        return isBaa;
    }

    public void setIsBaa(Integer isBaa) {
        this.isBaa = isBaa;
    }

    public Integer getAa() {
        return aa;
    }

    public void setAa(Integer aa) {
        this.aa = aa;
    }

}
